// Cron times are UTC: 01:00 UTC is 09:00 in Asia/Shanghai.
export const NEWS_CRON = '0 1 * * *'
export const NEWS_KEY = 'seedance-news:v1'
export const NEWS_SOURCES = [
  'https://seed.bytedance.com/en/blog_list/visual',
  'https://seed.bytedance.com/en/models',
  'https://seed.bytedance.com/zh/blog_list/visual',
  'https://seed.bytedance.com/zh/models',
]
const MAX_SOURCE_BYTES = 2_000_000
const MAX_ITEMS = 40
const TARGET = /\bseedance[\s_-]*3(?:[._-]0)?(?![a-z\d]|[._-]\d)/i

type Locale = 'en' | 'zh'
type Localized = Partial<Record<Locale, string>>
export interface NewsItem {
  id: string
  kind: 'announcement' | 'model-listing'
  title: Localized
  url: Localized
  publishedDate: string | null
  firstSeenAt: string
  fingerprint: string
}
type Candidate = Omit<NewsItem, 'firstSeenAt' | 'fingerprint'>
export interface NewsState {
  version: 1
  items: NewsItem[]
  lastCheckedAt: string
  lastSuccessfulCheckAt: string | null
  lastChangedAt: string | null
  sources: { url: string; ok: boolean }[]
}
// The deployed binding is generated by Wrangler; this narrow interface also permits isolated tests.
export interface NewsStorage {
  get(key: string, type: 'json'): Promise<unknown>
  put(key: string, value: string): Promise<unknown>
}
function object(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}
}
function text(value: unknown) {
  return typeof value === 'string' ? value.replace(/\s+/g, ' ').trim().slice(0, 300) : ''
}
export function chinaDate(value: string | Date) {
  return new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Shanghai', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date(value))
}
function trustedUrl(value: unknown): value is string {
  if (typeof value !== 'string' || value.length > 1500) return false
  try {
    const url = new URL(value)
    return url.origin === 'https://seed.bytedance.com' && /^\/(?:en|zh)\/(?:blog\/[^/]+|seedance[^/]*)$/.test(url.pathname)
      && !url.username && !url.password && !url.search && !url.hash
  } catch { return false }
}
function originalUrl(locale: Locale, slug: string) {
  return `https://seed.bytedance.com/${locale}/blog/${encodeURIComponent(slug)}`
}

export function parseOfficialBlog(html: string, now = new Date()): Candidate[] {
  // Read the site's serialized loader data as JSON. Never evaluate the remote script.
  const script = html.match(/<script\b[^>]*>\s*window\._ROUTER_DATA\s*=\s*([\s\S]*?)<\/script>/i)
  if (!script) throw new Error('Official blog structure was not recognized')
  let data: Record<string, unknown>
  try { data = object(JSON.parse(script[1].trim().replace(/;$/, ''))) }
  catch { throw new Error('Official blog structure contains invalid JSON') }
  const pages = Object.values(object(data.loaderData)).map(object)
  const page = pages.find(entry => entry.category === 'visual' && Array.isArray(entry.article_list))
  if (!page) throw new Error('Official blog structure has no visual article list')
  const articles = page.article_list as unknown[]
  if (articles.length > 100) throw new Error('Official blog structure exceeds the expected list size')
  return articles.flatMap(entry => {
    const article = object(entry)
    const meta = object(article.ArticleMeta)
    const en = object(article.ArticleSubContentEn)
    const zh = object(article.ArticleSubContentZh)
    const enTitle = meta.StatusEn === 2 ? text(en.Title) : ''
    const zhTitle = meta.StatusZh === 2 ? text(zh.Title) : ''
    if (meta.Status !== 2 || (!TARGET.test(enTitle) && !TARGET.test(zhTitle))) return []
    if (typeof meta.ArticleID !== 'number' || !Number.isSafeInteger(meta.ArticleID)) return []
    const enSlug = text(en.TitleKey)
    const zhSlug = text(zh.TitleKey)
    const english = enTitle && enSlug ? { en: enTitle } : {}
    const chinese = zhTitle && zhSlug ? { zh: zhTitle } : {}
    if (!english.en && !chinese.zh) return []
    let publishedDate: string | null = null
    if (typeof meta.PublishDate === 'number' && meta.PublishDate > 0) {
      if (meta.PublishDate > now.getTime()) return []
      publishedDate = chinaDate(new Date(meta.PublishDate))
    }
    return [{
      id: `blog:${meta.ArticleID}`, kind: 'announcement' as const,
      title: { ...english, ...chinese },
      url: { ...(english.en ? { en: originalUrl('en', enSlug) } : {}), ...(chinese.zh ? { zh: originalUrl('zh', zhSlug) } : {}) },
      publishedDate,
    }]
  })
}

export function parseOfficialModels(html: string, locale: Locale = 'en'): Candidate[] {
  const headings = [...html.matchAll(/<h[1-4]\b[^>]*>([\s\S]*?)<\/h[1-4]>/gi)]
    .map(match => text(match[1].replace(/<[^>]*>/g, ' ')))
  if (!headings.some(heading => /\bSeedance\s+[\d.]+\b/i.test(heading))) {
    throw new Error('Official models structure has no recognizable Seedance heading')
  }
  const title = headings.find(heading => TARGET.test(heading))
  if (!title) return []
  const links = [...html.matchAll(/href=["']([^"']+)["']/gi)].map(match => {
    try { return new URL(match[1], NEWS_SOURCES[1]).href } catch { return '' }
  })
  const pattern = new RegExp(`/${locale}/seedance3(?:[_-]0)?/?$`, 'i')
  const url = links.find(link => trustedUrl(link) && pattern.test(new URL(link).pathname))
  if (!url) throw new Error('Official models structure mentions 3.0 without a matching model link')
  return [{ id: 'model:seedance-3', kind: 'model-listing', title: { [locale]: title }, url: { [locale]: url }, publishedDate: null }]
}

async function boundedHtml(response: Response) {
  if (!response.ok || response.status >= 300 || !response.body) throw new Error('Official source unavailable')
  const reader = response.body.getReader()
  const decoder = new TextDecoder()
  let bytes = 0
  let html = ''
  try {
    for (;;) {
      const { done, value } = await reader.read()
      if (done) break
      bytes += value.byteLength
      if (bytes > MAX_SOURCE_BYTES) { await reader.cancel(); throw new Error('Official source too large') }
      html += decoder.decode(value, { stream: true })
    }
    return html + decoder.decode()
  } finally { reader.releaseLock() }
}
function timestamp(value: unknown): value is string {
  return typeof value === 'string' && /^\d{4}-\d{2}-\d{2}T/.test(value) && Number.isFinite(Date.parse(value))
}
export async function readNewsState(storage: NewsStorage): Promise<NewsState | null> {
  const value = await storage.get(NEWS_KEY, 'json')
  if (value === null) return null
  const state = object(value)
  const validItems = Array.isArray(state.items) && state.items.length <= MAX_ITEMS && state.items.every(value => {
    const item = object(value), title = object(item.title), url = object(item.url)
    return typeof item.id === 'string' && item.id.length < 100
      && ['announcement', 'model-listing'].includes(String(item.kind))
      && ['en', 'zh'].some(locale => typeof title[locale] === 'string' && trustedUrl(url[locale]))
      && ['en', 'zh'].every(locale => (title[locale] === undefined && url[locale] === undefined)
        || (typeof title[locale] === 'string' && String(title[locale]).length <= 300 && trustedUrl(url[locale])))
      && (item.publishedDate === null || (typeof item.publishedDate === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(item.publishedDate)))
      && timestamp(item.firstSeenAt) && typeof item.fingerprint === 'string' && /^[a-f\d]{64}$/.test(item.fingerprint)
  })
  if (state.version !== 1 || !validItems || !timestamp(state.lastCheckedAt)
    || !(state.lastChangedAt === null || timestamp(state.lastChangedAt))
    || !(state.lastSuccessfulCheckAt === null || timestamp(state.lastSuccessfulCheckAt))
    || !Array.isArray(state.sources) || state.sources.length !== NEWS_SOURCES.length
    || new Set(state.sources.map(value => object(value).url)).size !== NEWS_SOURCES.length
    || !state.sources.every(value => NEWS_SOURCES.includes(String(object(value).url)) && typeof object(value).ok === 'boolean')) {
    throw new Error('Stored official news failed validation')
  }
  return value as NewsState
}
async function fingerprint(candidate: Candidate) {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(JSON.stringify(candidate)))
  return Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, '0')).join('')
}
export async function collectSeedanceNews(storage: NewsStorage, options: { now?: Date; fetchImpl?: typeof fetch } = {}): Promise<NewsState> {
  const now = options.now ?? new Date()
  const checkedAt = now.toISOString()
  const fetchImpl = options.fetchImpl ?? fetch
  const previous = await readNewsState(storage)
  const results = await Promise.all(NEWS_SOURCES.map(async url => {
    try {
      const response = await fetchImpl(url, {
        redirect: 'manual', signal: AbortSignal.timeout(20_000),
        headers: { accept: 'text/html', 'user-agent': 'Seedance3-OfficialNewsTracker/1.0 (+https://seedance3-pro.com/seedance-3-0-release-date)' },
      })
      const html = await boundedHtml(response)
      return { url, ok: true, items: url.includes('/blog_list/') ? parseOfficialBlog(html, now) : parseOfficialModels(html, url.includes('/zh/') ? 'zh' : 'en') }
    } catch {
      console.warn(JSON.stringify({ event: 'seedance_news_source_failed', url }))
      return { url, ok: false, items: [] as Candidate[] }
    }
  }))
  const items = new Map((previous?.items ?? []).map(item => [item.id, item]))
  const discovered = new Map<string, Candidate>()
  for (const result of results) for (const candidate of result.items) {
    const old = discovered.get(candidate.id)
    const title = { ...old?.title }, url = { ...old?.url }
    for (const locale of ['en', 'zh'] as const) {
      // Each locale's page is authoritative for its own original title/link.
      if (candidate.title[locale] && candidate.url[locale] && (!title[locale] || result.url.includes(`/${locale}/`))) {
        title[locale] = candidate.title[locale]
        url[locale] = candidate.url[locale]
      }
    }
    discovered.set(candidate.id, { ...candidate, title, url })
  }
  for (const candidate of discovered.values()) {
    const old = items.get(candidate.id)
    const merged = { ...candidate, title: { ...old?.title, ...candidate.title }, url: { ...old?.url, ...candidate.url } }
    for (const locale of ['en', 'zh'] as const) {
      const path = candidate.kind === 'announcement' ? 'blog_list/visual' : 'models'
      const authoritative = results.find(result => result.url === `https://seed.bytedance.com/${locale}/${path}`)
      if (!authoritative?.ok && old?.title[locale] && old.url[locale]) {
        // A failed source must not roll its saved title back to another locale's older copy.
        merged.title[locale] = old.title[locale]
        merged.url[locale] = old.url[locale]
      }
    }
    const hash = await fingerprint(merged)
    if (old?.fingerprint === hash) continue
    items.set(candidate.id, { ...merged, firstSeenAt: old?.firstSeenAt ?? checkedAt, fingerprint: hash })
  }
  const nextItems = [...items.values()].sort((a, b) => (b.publishedDate ?? chinaDate(b.firstSeenAt)).localeCompare(a.publishedDate ?? chinaDate(a.firstSeenAt)) || a.id.localeCompare(b.id)).slice(0, MAX_ITEMS)
  const signatures = (entries: NewsItem[]) => JSON.stringify(entries.map(item => [item.id, item.fingerprint]))
  const changed = signatures(nextItems) !== signatures(previous?.items ?? [])
  const state: NewsState = {
    version: 1,
    items: nextItems,
    lastCheckedAt: checkedAt,
    lastSuccessfulCheckAt: results.every(result => result.ok) ? checkedAt : previous?.lastSuccessfulCheckAt ?? null,
    lastChangedAt: changed ? checkedAt : previous?.lastChangedAt ?? null,
    sources: results.map(({ url, ok }) => ({ url, ok })),
  }
  await storage.put(NEWS_KEY, JSON.stringify(state))
  console.log(JSON.stringify({ event: 'seedance_news_checked', complete: results.every(result => result.ok), changed, count: state.items.length }))
  return state
}
